UsefulFood: fix item ID conflict with RedPower
java.lang.RuntimeException: RedPowerCore: ItemID 5071 exists, autoAssign is disabled.

UsefulFood uses IDs starting at 5050+, but RedPower goes up to 5068. Change UsefulFood to start at 5150+.